CREATE DATABASE synth;
CREATE TABLE configs (
    guildID VARCHAR(100) NOT NULL PRIMARY KEY,
    guildOwnerID VARCHAR(100) NOT NULL,
    prefix VARCHAR(10) DEFAULT '!',
    color VARCHAR(7) DEFAULT '#FFFFFF'
);